services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 2020:2020
    volumes:
      - /home/gdoumer/data/wordpress:/var/www/html
      - /run/php:/run/php
    restart: always
    networks:
      - net

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/gdoumer/data/mariadb:/var/lib/mysql
    networks:
      - net
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - nginx
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - /home/gdoumer/data/wordpress:/var/www/html
      - /run/php:/run/php
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
